import './base.css'
import { Manrope } from 'next/font/google'

const font = Manrope({ subsets: ['latin'] })

export const metadata = {
  title: 'Nick Beuchat | Creative Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        {children}
      </body>
    </html>
  )
}
